services:
  availdomain:
    container_name: availdomain
    build:
      context: ../../
      dockerfile: ./docker/development/DockerFile
      target: dev
    image: avail-domain-app
    volumes:
      - ../../:/home/node/app
    working_dir: /home/node/app
    # command: bash -c "npm i && npm run dev"
    command: bash -c "npm i && tail -f /dev/null"
    ports:
      - 3001:3000
