ARG NODE_VERSION=20.17.0
ARG LINUX_DISTRO=alpine3.20

FROM node:${NODE_VERSION}-${LINUX_DISTRO} AS base
# Check https://github.com/nodejs/docker-node/tree/b4117f9333da4138b03a546ec926ef50a31506c3#nodealpine to understand why libc6-compat might be needed.
RUN apk add --no-cache libc6-compat
RUN apk add --no-cache --upgrade bash

FROM base AS dev
ENV NODE_ENV=development
