#!/usr/bin/env bash
set -euo pipefail

SERVICE_NAME="web"

function show_help() {
  echo
  echo "Usage:"
	echo
  echo "  $0 start              Start the development server"
  echo "  $0 stop               Stop the development server"
	echo "  $0 restart            Restart the development server"
  echo "  $0 enter              Enter the container shell"
	echo "  $0 logs               Show service logs"
  echo "  $0 ps                 List running services"
  echo "  $0 docker <command>   Run command inside the container"
  echo
  exit 0
}

if [[ $# -eq 0 ]]; then
  show_help
fi

case "$1" in
  help|-h|--help)
    show_help
    ;;
  start)
    docker compose up -d --build \
    && docker compose exec "$SERVICE_NAME" sh
    ;;
  stop)
    docker compose down
    ;;
	restart)
		docker compose restart "$SERVICE_NAME"
	;;
  enter)
		docker compose exec "$SERVICE_NAME" sh
		;;
	logs)
		docker compose logs "$SERVICE_NAME" -f
		;;
  ps)
    docker compose ps
    ;;
  docker)
    shift 2
    docker compose exec "$SERVICE_NAME" "$@"
    ;;
esac
